spring.application.name=hr_portal
server.port=9090
management.endpoints.web.exposure.include=health,info,metrics
management.graphite.metrics.export.enabled=true
management.graphite.metrics.export.host=host.docker.internal
management.graphite.metrics.export.port=2003
management.graphite.metrics.export.step=10s