apiVersion: apps/v1
kind: Deployment

metadata:
  name: hr-portal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hr-portal

  template:
    metadata:
      labels:
        app: hr-portal

    spec:
      hostAliases:
        - ip: "192.168.1.7:"   # Replace with the IP returned by: ping host.docker.internal
          hostnames:
            - "host.docker.internal"

      containers:
        - name: hr-portal
          image: hr-portal:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 9090