apiVersion: v1
kind: Service

metadata:
  name: hr-portal-service

spec:
  type: NodePort

  selector:
    app: hr-portal

  ports:
    - name: app
      protocol: TCP
      port: 8081
      targetPort: 9090
      nodePort: 30081

    - name: actuator
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090