apiVersion: v1
kind: Service

metadata:
  name: hr-portal-service
  namespace: default
  labels:
    app: hr-portal
    component: cloud-reliability-platform

spec:
  type: NodePort

  selector:
    app: hr-portal

  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090

    - name: app-alt
      protocol: TCP
      port: 8081
      targetPort: 9090
      nodePort: 30081